#ifndef SOFT_UART_H_INCLUDED
#define SOFT_UART_H_INCLUDED

#include <avr/io.h>

typedef void (*suart_rx_handler_t)(uint8_t);

#define BAUD_RATE 57600
#define SUART_BITS 8

#define RX_PINX PIND
#define RX_PORTX PORTD
#define RX_DDRX DDRD
#define RX_PIN 2  

#define TX_PORTX PORTD
#define TX_DDRX DDRD
#define TX_PIN 4

#define get_rx_pin_status() RX_PINX & _BV(RX_PIN)
#define set_tx_pin_high() TX_PORTX |= _BV(TX_PIN)
#define set_tx_pin_low() TX_PORTX &= ~_BV(TX_PIN)

#define ENABLE_EXTERNAL0_INTERRUPT() (GICR |= _BV(INT0))
#define DISABLE_EXTERNAL0_INTERRUPT() (GICR &= ~_BV(INT0))
#define CLEAR_EXTERNAL0_INTERRUPT() (GIFR = _BV(INTF0))

#define ENABLE_EXTERNAL1_INTERRUPT() (GICR |= _BV(INT1))
#define DISABLE_EXTERNAL1_INTERRUPT() (GICR &= ~_BV(INT1))
#define CLEAR_EXTERNAL1_INTERRUPT() (GIFR = _BV(INTF1))

#define ENABLE_TIMER2_INTERRUPT() (TIMSK |= _BV(OCIE2))
#define DISABLE_TIMER2_INTERRUPT() (TIMSK &= ~_BV(OCIE2))
#define CLEAR_TIMER2_INTERRUPT() (TIFR = _BV(OCF2))

#define ENABLE_TIMER1_INTERRUPT() (TIMSK |= _BV(OCIE1A))
#define DISABLE_TIMER1_INTERRUPT() (TIMSK &= ~_BV(OCIE1A))
#define TEST_TIMER1_INTERUPT() (TIMSK & _BV(OCIE1A))
#define CLEAR_TIMER1_INTERRUPT() (TIFR = _BV(OCF1A))

#if (RX_PIN == 2)
#define EXTINT_VECTOR INT0_vect
#define EXTINT_SET_INT_SENSE_CONTOL(x) extint_set_int0_sense_control(x)
#define ENABLE_EXTERNAL_INTERRUPT() ENABLE_EXTERNAL0_INTERRUPT()
#define DISABLE_EXTERNAL_INTERRUPT() DISABLE_EXTERNAL0_INTERRUPT()
#define CLEAR_EXTERNAL_INTERRUPT() CLEAR_EXTERNAL0_INTERRUPT()
#elif (RX_PIN == 3)
#define EXTINT_VECTOR INT1_vect
#define EXTINT_SET_INT_SENSE_CONTOL(x) extint_set_int1_sense_control(x)
#define ENABLE_EXTERNAL_INTERRUPT() ENABLE_EXTERNAL1_INTERRUPT()
#define DISABLE_EXTERNAL_INTERRUPT() DISABLE_EXTERNAL1_INTERRUPT()
#define CLEAR_EXTERNAL_INTERRUPT() CLEAR_EXTERNAL1_INTERRUPT()
#else
#error "Only INT0 and INT1 supported for software UART"
#endif

#define TICKS2WAITONE ((F_CPU/BAUD_RATE/8)-1)
#define TICKS2WAITONE_HALF (TICKS2WAITONE + (TICKS2WAITONE/2)) 
#define INTERRUPT_EXEC_CYCL 2
#define TX_INTERRUPT_EXEC_CYCL 16

extern void SUART_Init(suart_rx_handler_t handler);
extern void SUART_PutChar(uint8_t ch);

#endif 
